name: Debricked

on: [push]    

jobs:
  debricked:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:     
     - uses: actions/checkout@v3
     - uses: debricked/actions/callgraph@v3
     - run: |
          ls
     - uses: debricked/actions@v3
       env:
          DEBRICKED_TOKEN: 'be675ce5225ddb0416bf544e19bbacc8d526a24e8c4a73f5'
          DEBRICKED_URI: 'https://review-6831-reach-qc4gm9.review.debricked.dev'
